// @ts-check

// 此文件在Node.js环境运行 - 不要使用客户端代码（如浏览器API、JSX等）

/**
 * 创建侧边栏可让你：
 *  - 创建有序的文档组
 *  - 为每个文档组渲染侧边栏
 *  - 提供上/下一篇导航功能
 * 
 * 侧边栏可以从文件系统自动生成，或在此处显式定义。
 * 可以根据需要创建任意数量的侧边栏。
 * 
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // 默认配置：Docusaurus会根据docs文件夹的结构自动生成侧边栏
  // 会扫描docs目录下的所有文件和子目录，并按层级生成侧边栏
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // 手动配置示例：完全自定义侧边栏结构（取消注释下方代码可使用）
  /*
  tutorialSidebar: [
    'intro', // 直接引用docs/intro.mdx文件（ID为'intro'）
    'hello', // 引用docs/hello.mdx文件
    
    // 创建一个文档分类（会在侧边栏显示为折叠/展开的分组）
    {
      type: 'category',
      label: 'Tutorial', // 分类名称（显示在侧边栏）
      items: ['tutorial-basics/create-a-document'], // 分类下的文档列表
    },
  ],
   */
};

export default sidebars;
